2022-08-14 21:48:59,206 INFO    MainThread:16856 [wandb_setup.py:_flush():76] Configure stats pid to 16856
2022-08-14 21:48:59,206 INFO    MainThread:16856 [wandb_setup.py:_flush():76] Loading settings from C:\Users\GuillemUPV\.config\wandb\settings
2022-08-14 21:48:59,206 INFO    MainThread:16856 [wandb_setup.py:_flush():76] Loading settings from f:\TFG\code\wandb\settings
2022-08-14 21:48:59,206 INFO    MainThread:16856 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_service': 'True'}
2022-08-14 21:48:59,206 INFO    MainThread:16856 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-08-14 21:48:59,207 INFO    MainThread:16856 [wandb_init.py:_log_setup():461] Logging user logs to f:\TFG\code\wandb\run-20220814_214859-22yujsj9\logs\debug.log
2022-08-14 21:48:59,207 INFO    MainThread:16856 [wandb_init.py:_log_setup():462] Logging internal logs to f:\TFG\code\wandb\run-20220814_214859-22yujsj9\logs\debug-internal.log
2022-08-14 21:48:59,207 INFO    MainThread:16856 [wandb_init.py:init():495] calling init triggers
2022-08-14 21:48:59,207 INFO    MainThread:16856 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2022-08-14 21:48:59,207 INFO    MainThread:16856 [wandb_init.py:init():514] re-initializing run, found existing run on stack: 2spac9im
2022-08-14 21:48:59,209 INFO    MainThread:16856 [wandb_run.py:_finish():1728] finishing run prunonos/sportanalytycs/2spac9im
2022-08-14 21:48:59,209 INFO    MainThread:16856 [jupyter.py:save_history():435] not saving jupyter history
2022-08-14 21:48:59,209 INFO    MainThread:16856 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-08-14 21:48:59,209 INFO    MainThread:16856 [wandb_init.py:_jupyter_teardown():393] cleaning up jupyter logic
2022-08-14 21:48:59,210 INFO    MainThread:16856 [wandb_run.py:_atexit_cleanup():1931] got exitcode: 0
2022-08-14 21:48:59,210 INFO    MainThread:16856 [wandb_run.py:_restore():1914] restore
2022-08-14 21:48:59,210 INFO    MainThread:16856 [wandb_run.py:_restore():1920] restore done
2022-08-14 21:48:59,215 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 541
  total_bytes: 541
}

2022-08-14 21:48:59,350 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 541
  total_bytes: 541
}

2022-08-14 21:49:04,467 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:49:09,583 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:49:14,704 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:49:19,818 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:49:24,936 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:49:30,053 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:49:35,169 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:49:40,285 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:49:45,403 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:49:50,517 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:49:55,628 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:50:00,747 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:50:05,862 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:50:10,974 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:50:16,087 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:50:21,201 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:50:26,319 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:50:31,427 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:50:36,551 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:50:41,667 INFO    MainThread:16856 [wandb_run.py:_on_finish():2221] got exit ret: None
2022-08-14 21:50:46,791 INFO    MainThread:16856 [wandb_init.py:init():548] starting backend
2022-08-14 21:50:46,791 INFO    MainThread:16856 [wandb_init.py:init():552] setting up manager
2022-08-14 21:50:46,793 INFO    MainThread:16856 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2022-08-14 21:50:46,794 INFO    MainThread:16856 [wandb_init.py:init():558] backend started and connected
2022-08-14 21:50:46,806 INFO    MainThread:16856 [wandb_run.py:_label_probe_notebook():1105] probe notebook
2022-08-14 21:50:46,806 INFO    MainThread:16856 [wandb_run.py:_label_probe_notebook():1115] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-08-14 21:50:46,807 INFO    MainThread:16856 [wandb_init.py:init():636] updated telemetry
2022-08-14 21:50:46,807 INFO    MainThread:16856 [wandb_init.py:init():667] communicating run to backend with 30 second timeout
